name: "Test"
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Setup Node"
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: "Bump version"
        run: |
          export VERSION="1.$(echo ${GITHUB_SHA:0:4} | tr abcdef 123456).$(echo ${GITHUB_SHA:4:4} | tr abcdef 123456)"
          jq ".version = \"$VERSION\"" test/extension/manifest.json > manifest.json~
          mv manifest.json~ test/extension/manifest.json
          git diff

      - name: "Sign"
        id: web-ext-sign
        uses: "./"
        with:
          apiKey: ${{ secrets.API_KEY }}
          apiSecret: ${{ secrets.API_SECRET }}
          sourceDir: "test/extension"

      - name: "Upload xpi"
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.web-ext-sign.outputs.name }}
          path: ${{ steps.web-ext-sign.outputs.path }}
